schema:
  - ./boot/src/test/resources/graphql/schema.graphqls
  - '**/main/resources/**/*.graphqls'
extensions:
  endpoints:
    Gatsby GraphQL Endpoint:
      url: http://localhost:8080/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
