package cn.asany.shanhai.core.domain.enums;

public enum ModelConnectType {
  GRAPHQL_INPUT_CREATE,
  GRAPHQL_INPUT_UPDATE,
  GRAPHQL_INPUT_WHERE,
  GRAPHQL_ENUM_ORDER_BY,
  GRAPHQL_OBJECT_EDGE,
  GRAPHQL_OBJECT_CONNECTION,
}
