version: "3.3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - server
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /app/asany/mysql/data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: yV2jJxvNs8BD
  server:
    depends_on:
      - db
    links:
      - db
    image: limaofeng/asany-server:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      spring.profiles.active: prod
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: yV2jJxvNs8BD
      DATABASE_INSTANCE_NAME: asany
      DATABASE_HOST: db
