version: '3.3'
services:
  db:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    volumes:
      - '/srv/asany/mysql/data:/var/lib/mysql'
      - './database:/docker-entrypoint-initdb.d/'
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: yV2jJxvNs8BD
  server:
    depends_on:
      - db
    links:
      - db
    image: 'limaofeng/asany-server:latest'
    ports:
      - '80:8080'
    restart: always
    environment:
      spring.profiles.active: prod
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: yV2jJxvNs8BD
      DATABASE_INSTANCE_NAME: asany
      DATABASE_HOST: db
