spring:
  jfantasy:
    sequence:
      pool-size: 100
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://dev.local:3306/asany?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: yV2jJxvNs8BD
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 10
  redis:
    host: 139.196.223.217
    port: 31134