spring:
  jfantasy:
    sequence:
      pool-size: 1
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://api.thuni-h.com:30306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: CU:4icgD4MF6Q!u^
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1
  redis:
    database: 0
    host: api.dev.thuni-h.com
    port: 32519
    password: Y0HfNA{PdjSINZyy

storage:
  url: http://demo.homeword.cn/files