spring:
  jfantasy:
    sequence:
      pool-size: 100
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://127.0.0.1:3306/asany?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: yV2jJxvNs8BD
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379