spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: server
  sequence:
    pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    name: datasource
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_INSTANCE_NAME}?nullCatalogMeansCurrent=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
    proxy: true
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  quartz:
    properties:
      org:
        quartz:
          dataSource:
            qzDS:
              URL: jdbc:mysql://${DATABASE_HOST}/${DATABASE_INSTANCE_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
              driver: com.mysql.cj.jdbc.Driver
              user: ${DATABASE_USERNAME}
              password: ${DATABASE_PASSWORD}
  flyway:
    url: jdbc:mysql://${DATABASE_HOST}/mysql?useUnicode=true&characterEncoding=UTF-8
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    schemas: ${DATABASE_INSTANCE_NAME}

openim:
  url: ${OPENIM_SERVER}
  secret: ${OPENIM_SECRET}
  admin:
    user: ${OPENIM_ADMIN}

sms:
  provider:
    aliyun:
      accessKeyId: ${ALIYUN_ACCESSKEY_ID}
      accessKeySecret: ${ALIYUN_ACCESSKEY_SECRET}