spring:
  jfantasy:
    sequence:
      pool-size: 100
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/asany?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: yV2jJxvNs8BD
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1
  redis:
    database: 0
    host: api.dev.thuni-h.com
    port: 32519
    password: Y0HfNA{PdjSINZyy